device:
- 0
model: net.st_gcn.Model
model_args:
  edge_importance_weighting: true
  graph_args:
    layout: coco
    strategy: spatial
  in_channels: 3
  num_class: 4
model_fps: 30
weights: ./models/latest.pth
